#!/bin/bash

function print_help() {
    res=${1:-0}
    echo "Usage klee.env [FLAGS] VARIABLES"
    echo "Prints the variables needed to compile klee programs"
    echo ""
    echo "Available FLAGS:"
    echo "  -h, --help                  Display this help and exit."
    echo ""
    echo "Available VARIABLES:"
    echo "    CFLAGS  returns the flags to pass to clang or gcc with"
    echo "            include/lib paths to compile a klee program."
    echo "    LDFLAGS returns the link flags to pass to clang or gcc"
    echo "            to link a klee program, so that it can run the"
    echo "            testcases generated by a klee run."
    echo ""
    exit $res
}

DIR="$( realpath "$( dirname -- "${BASH_SOURCE[0]}"; )/.." )"

command=

while [ "$1" != "$EOL" ]; do
    opt="$1"; shift
    case $opt in
     -h | --help) print_help;;
     *          ) command=$opt;;
    esac
done


case $command in
 CFLAGS )
    echo "-I $DIR/include -L $DIR/lib"
    ;;
 LDFLAGS)
    echo "-lkleeRuntest"
    ;;
 *      )
    >&2 echo "Error: unknown variable $command"
    print_help 1
    ;;
esac
 
